            - name: run_pylint
  # You may pin to the exact commit or the version.
  # uses: colevandersWands/run_pylint@2bd87297962de9e08da0b0cebd4e08fac0ab5d6e
  uses: colevandersWands/run_pylint@v1.0.2
  with:
    # 
    options: # optional, default is 
    # command used to install python dependancies
    pip_install_command: # optional, default is pip install pylint
    # version of python to run action with
    python_version: # optional, default is 3.x
    # 
    src: # optional, default is .
          
